Global:
  enableFallDamage: false
DoubleJump:
  type: dash
  # 3 types: dash, up, levitation
  power: 0.5
  message: ""
  particles: FLAME
  particlesCount: 40
  sound: ENTITY_GHAST_SHOOT
  soundVolume: 70
  soundPitch: 0
